{
 "title": "ReInvent Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queries Per Second",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vttablet_query_counts[1m]))"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Network Out",
     "dimensions": {
      "AutoScalingGroupName": "vitess-eks-node-vitess20181029233758286200000001"
     },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Network In",
     "dimensions": {
      "AutoScalingGroupName": "vitess-eks-node-vitess20181029233758286200000001"
     },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "metricName": "NetworkOut", "namespace": "AWS/EC2", "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Query Latency (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(vtgate_mysql_server_timings_bucket[10m])) by (operation,le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vtgate_mysql_server_timings_bucket[10m])) by (operation,le))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Avg Memory Utilization",
   "type": "graph",
   "description": "Memory Utilization",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes [5m]) + avg_over_time(node_memory_Cached_bytes[5m]) + avg_over_time(node_memory_Buffers_bytes[5m])) / avg_over_time(node_memory_MemTotal_bytes[5m]))))\n",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Avg CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Read & Write bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Disk Read",
     "dimensions": {
      "AutoScalingGroupName": "vitess-eks-node-vitess20181029233758286200000001"
     },
     "id": "dr",
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Disk Write",
     "dimensions": {
      "AutoScalingGroupName": "vitess-eks-node-vitess20181029233758286200000001"
     },
     "id": "dw",
     "metricName": "DiskWriteBytes",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}